language: dart
dart:
  - stable
os:
  - linux
sudo: false
matrix:
  include:
    - name: Test
      env: COMMAND=test
    - name: Analyze
      env: COMMAND=analyze
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6
install:
  - echo 'Running tests...'
  - pwd
before_script:
  - cd ..
  - if [ ! -f $HOME/flutter/bin/flutter ] ; then git clone https://github.com/flutter/flutter.git -b stable ; fi
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - gem install coveralls-lcov
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter $COMMAND
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - flutter
    - $HOME/.pub-cache
