name: vlop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  font_awesome_flutter: ^8.8.1
  string_validator: ^0.1.4
  flutter_spinkit: ^4.1.2+1
  firebase_admin_interop: ^2.1.0
  image_picker: ^0.6.5
  uuid: ^2.0.4
  image_cropper: ^1.2.1
  rxdart: ^0.24.0
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  flare_flutter: ^2.0.3
  cached_network_image: ^2.2.0+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  assets:
    # Animation from https://rive.app/a/pollux/files/flare/success-check/preview
    - assets/checkmark.flr
    - assets/images/default.jpg
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Light.ttf
          weight: 300
